const TourData = [
  {
    id: '1',
    cardPicture: 'card__picture card__picture--1',
    cardHeading: 'card__heading--main card__heading--main-1',
    cardHead: 'The sea',
    cardSubing: 'card__heading--sub card__heading--sub-1',
    cardSub: 'Explorer',
    list1: '3 days tour',
    list2: 'Up to 30 people',
    list3: '2 tour guides',
    list4: 'Sleeping cozy hotels',
    list5: 'Difficulty: Easy',
    cardBack: 'card__side card__side--back card__side--back-1',
    cardbText: 'card__back-content--text card__back-content--text-1',
    cardbPrice: 'card__back-content--price card__back-content--price-1',
    price: '$297',
  },
  {
    id: '2',
    cardPicture: 'card__picture card__picture--2',
    cardHeading: 'card__heading--main card__heading--main-2',
    cardHead: 'The forest',
    cardSubing: 'card__heading--sub card__heading--sub-2',
    cardSub: 'Hiker',
    list1: '7 days tour',
    list2: 'Up to 40 people',
    list3: '6 tour guides',
    list4: 'Sleep in provided tents',
    list5: 'Difficulty: Medium',
    cardBack: 'card__side card__side--back card__side--back-2',
    cardbText: 'card__back-content--text card__back-content--text-2',
    cardbPrice: 'card__back-content--price card__back-content--price-2',
    price: '$459',
  },
  {
    id: '3',
    cardPicture: 'card__picture card__picture--3',
    cardHeading: 'card__heading--main card__heading--main-3',
    cardHead: 'The snow',
    cardSubing: 'card__heading--sub card__heading--sub-3',
    cardSub: 'Adventurer',
    list1: '5 days tour',
    list2: 'Up to 15 people',
    list3: '3 tour guides',
    list4: 'Sleep in provided tents',
    list5: 'Difficulty: Hard',
    cardBack: 'card__side card__side--back card__side--back-3',
    cardbText: 'card__back-content--text card__back-content--text-3',
    cardbPrice: 'card__back-content--price card__back-content--price-3',
    price: '$784',
  },
]

export default TourData;
