const LuxuryData =[
  {
    id:1,
    luxuryname: 'Mercedes',
    image: './../../../images/mercedes.png',
    dealerDetails: 'ope lenge car dealer no one can dare',
    location: 'USA',
    price: 900000,
    fuel: 'Electric',
    power: '480-560 hp',
  },
  {
    id:2,
    luxuryname: 'Swift',
    image: './../../../images/swift.png',
    dealerDetails: 'bad ass car sales expert',
    location: 'Germany',
    price: 850000,
    fuel: 'Electric',
    power: '380-490 hp',
  },
  {
    id:3,
    luxuryname: 'G class',
    image: './../../../images/gclass.png',
    dealerDetails: 'ope lenge car dealer no one can dare',
    location: 'Sweden',
    price: 650000,
    fuel: 'Electric',
    power: '380-500 hp',
  },
  {
    id:4,
    luxuryname: 'BMW',
    image: './../../../images/bmw.png',
    dealerDetails: 'ope lenge car dealer no one can dare',
    location: 'Poland',
    price: 950000,
    fuel: 'Electric',
    power: '480-540 hp',
  },
  {
    id:5,
    luxuryname: 'Audi',
    image: './../../../images/audi.png',
    dealerDetails: 'ope lenge car dealer no one can dare',
    location: 'Poland',
    price: 550000,
    fuel: 'Gasoline',
    power: '320-440 hp',
  },
  {
    id:6,
    luxuryname: 'Antique Car',
    image: './../../../images/antique.png',
    dealerDetails: 'samuel of Lagos omo baba ahmed',
    location: 'USA',
    price: 800000,
    fuel: 'Gasoline',
    power: '330-450 hp',
  },
]

export default LuxuryData;
